---
title: "tabs"
output: html_document
---


```{r, echo=FALSE, results='asis'}
library(printr) 
Nu.Functions = matrix( 
   c("ciAS","ciASx","ciAAS","ciAASx","ciCAS","ciCASx","covpAS","covpAAS","covpCAS","lengthAS","lengthAAS","lengthCAS","pCOpBIAS","pCOpBIAAS","pCOpBICAS","errAS","errAAS","errCAS",
"ciLR","ciLRx","ciALR","ciALRx","","","covpLR","covpALR","","lengthLR","lengthALR","","pCOpBILR","pCOpBIALR","","errLR","errALR","",
"ciLT","ciLTx","ciALT","ciALTx","ciCLT","ciCLTx","covpLT","covpALT","covpCLT","lengthLT","lengthALT","lengthCLT","pCOpBILT","pCOpBIALT","pCOpBICLT","errLT","errALT","errCLT",
"ciSC","ciSCx","ciASC","ciASCx","ciCSC","ciCSCx","covpSC","covpASC","covpCSC","lengthSC","lengthASC","lengthCSC","pCOpBISC","pCOpBIASC","pCOpBICSC","errSC","errASC","errCSC",
"ciTW","ciTWx","ciATW","ciATWx","ciCTW","ciCTWx","covpTW","covpATW","covpCTW","lengthTW","lengthATW","lengthCTW","pCOpBITW","pCOpBIATW","pCOpBICTW","errTW","errATW","errCTW",
"ciWD","ciWDx","ciAWD","ciAWDx","ciCWD","ciCWDx","covpWD","covpAWD","covpCWD","lengthWD","lengthAWD","lengthCWD","pCOpBIWD","pCOpBIAWD","pCOpBICWD","errWD","errAWD","errCWD",
"ciAll","ciAllx","ciAAll","ciAAllx","ciCAll","ciCAllx","covpAll","covpAAll","covpCAll","lengthAll","lengthAAll","lengthCAll","pCOpBIAll","pCOpBIAAll","pCOpBICAll","errAll","errAAll","errCAll",
"ciBA","ciBAx","","","","","covpBA","","","lengthBA","","","pCOpBIBA","","","errBA","","",
"ciEX","ciEXx","","","","","covpEX","","","lengthEX","","","pCOpBIEX","","","errEX","",""
), 
   byrow=TRUE,
   nrow=9, 
   ncol=18)

colnames(Nu.Functions)=c("ci","cix","ciA","ciAx","ciC","ciCx","covp","covpA","covpC","length","Alength","Clength","pcpb","pcpbA","pcpbC","error","errorA","errorC")
rownames(Nu.Functions)=c("ArcSine", "LR","Logit","Score","Wald-T","Wald","All","Bayes","Exact")

knitr::kable(Nu.Functions)
```


```{r, echo=FALSE, results='asis'}
library(printr) 

Plot.Functions = matrix( c("PlotciAS","","PlotciAAS","","PlotciCAS","","PlotcovpAS","PlotcovpAAS","PlotcovpCAS","PlotlengthAS","PlotexplAS","PlotlengthAAS","PlotexplAAS","PlotlengthCAS","PlotexplCAS","PlotpCOpBIAS","PlotpCOpBIAAS","PlotpCOpBICAS","PloterrAS","PloterrAAS","PloterrCAS",
"PlotciLR","","PlotciALR","","","","PlotcovpLR","PlotcovpALR","","PlotlengthLR","PlotexplLR","PlotlengthALR","PlotexplALR","","","PlotpCOpBILR","PlotpCOpBIALR","","PloterrLR","PloterrALR","",
"PlotciLT","","PlotciALT","","PlotciCLT","","PlotcovpLT","PlotcovpALT","PlotcovpCLT","PlotlengthLT","PlotexplLT","PlotlengthALT","PlotexplALT","PlotlengthCLT","PlotexplCLT","PlotpCOpBILT","PlotpCOpBIALT","PlotpCOpBICLT","PloterrLT","PloterrALT","PloterrCLT",
"PlotciSC","","PlotciASC","","PlotciCSC","","PlotcovpSC","PlotcovpASC","PlotcovpCSC","PlotlengthSC","PlotexplSC","PlotlengthASC","PlotexplASC","PlotlengthCSC","PlotexplCSC","PlotpCOpBISC","PlotpCOpBIASC","PlotpCOpBICSC","PloterrSC","PloterrASC","PloterrCSC",
"PlotciTW","","PlotciATW","","PlotciCTW","","PlotcovpTW","PlotcovpATW","PlotcovpCTW","PlotlengthTW","PlotexplTW","PlotlengthATW","PlotexplATW","PlotlengthCTW","PlotexplCTW","PlotpCOpBITW","PlotpCOpBIATW","PlotpCOpBICTW","PloterrTW","PloterrATW","PloterrCTW",
"PlotciWD","","PlotciAWD","","PlotciCWD","","PlotcovpWD","PlotcovpAWD","PlotcovpCWD","PlotlengthWD","PlotexplWD","PlotlengthAWD","PlotexplAWD","PlotlengthCWD","PlotexplCWD","PlotpCOpBIWD","PlotpCOpBIAWD","PlotpCOpBICWD","PloterrWD","PloterrAWD","PloterrCWD",
"PlotciAllg","PlotciAllxg","PlotciAAllg","PlotciAAllxg","PlotciCAllg","PlotciCAllxg","","","","","","","","","","","","","","","",
"PlotciAll","PlotciAllx","PlotciAAll","PlotciAAllx","PlotciCAll","PlotciCAllx","PlotcovpAll","PlotcovpAAll","PlotcovpCAll","PlotlengthAll","PlotexplAll","PlotlengthAAll","PlotexplAAll","PlotlengthCAll","PlotexplCAll","PlotpCOpBIAll","PlotpCOpBIAAll","PlotpCOpBICAll","PloterrAll","PloterrAAll","PloterrCAll",
"PlotciBA","","","","","","PlotcovpBA","","","PlotlengthBA","PlotexplBA","","","","","PlotpCOpBIBA","","","PloterrBA","","",
"PlotciEX","PlotciEXx","","","","","PlotcovpEX","","","PlotlengthEX","PlotexplEX","","","","","PlotpCOpBIEX","","","PloterrEX","",""),byrow=TRUE, nrow=10,  ncol=21)


colnames(Plot.Functions)=c("ci","cix","ciA","ciAx","ciC","ciCx","covp","covpA","covpC","length","EL","Alength","AEL","Clength","CEL","pcpb","pcpbA","pcpbC","error","errorA","errorC")
rownames(Plot.Functions)=c("ArcSine", "LR","Logit","Score","Wald-T","Wald","All","Allg","Bayes","Exact")

knitr::kable(Plot.Functions)
```

